const tempData = [
  {
    name: "Pizza Hut",
    cloudinaryImageId: "19b555f364f7c5e0db9e815efb078b35",
    locality: "Shivpuri Road",
    areaName: "Civil Lines",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 4,
    id: "721",
    avgRatingString: "4.0",
    deliveryTime: 21,
  },
  {
    name: "Dominos",
    cloudinaryImageId: "d0450ce1a6ba19ea60cd724471ed54a8",
    locality: "Shivpuri Road",
    areaName: "Civil Lines",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "Hot Dog"],
    avgRating: 4,
    id: "722",
    avgRatingString: "4.9",
    deliveryTime: 23,
  },
  {
    name: "Sandwich Hut",
    cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
    locality: "Shivpuri Road",
    areaName: "Civil Lines",
    costForTwo: "₹350 for two",
    cuisines: ["Sandwich", "Noodles", "French Fries"],
    avgRating: 4,
    id: "723",
    avgRatingString: "3.6",
    deliveryTime: 32,
  },
  {
    name: "Pasta Hut",
    cloudinaryImageId: "d0450ce1a6ba19ea60cd724471ed54a8",
    locality: "Shivpuri Road",
    areaName: "Civil Lines",
    costForTwo: "₹350 for two",
    cuisines: ["Pasta", "Chowmin"],
    avgRating: 4,
    id: "724",
    avgRatingString: "4.4",
    deliveryTime: 26,
  },
];

export default tempData;